name: Bump Helm Chart
description: bumps a helm chart version from a github release
inputs:
  path:
    description: Path to the chart folder
    required: true
  release:
    description: The release tag to use as appVersion
    required: true
  github-token:
    description: the token to authenticate to github with
    required: false
  branch:
    description: The branch to commit and push to
    required: false
outputs: {}
runs:
  using: 'node12'
  main: 'index.js'